import type { NextConfig } from "next";
import bundleAnalyzer from "@next/bundle-analyzer";

const withBundleAnalyzer = bundleAnalyzer({
  enabled: process.env.ANALYZE === "true",
});

const nextConfig: NextConfig = {

  reactStrictMode: true, // ✅ Helps catch performance issues in dev
  experimental: {
    cssChunking: true,     // Split + reorder CSS per route
    optimizeCss: true,     // Inline critical CSS (Critters)
    inlineCss: true        // Alternative inlining flag present in newer versions
  },


  images: {
    // Disable all Next.js/Vercel image optimization globally
    unoptimized: false, // images will be served as-is, no optimizer requests [1][13]
    // Keep remotePatterns if still using <Image> with external sources (safe to keep)
    remotePatterns: [
      {
        protocol: "https",
        hostname: "secure.gravatar.com",
        port: "",
        pathname: "/avatar/**",
      },
      {
        protocol: "https",
        hostname: "cms.testriq.com",
        port: "",
        pathname: "/wp-content/uploads/**",
      },
      {
        protocol: "https",
        hostname: "cdn.sanity.io",
        port: "",
        pathname: "/images/**",
      },
      {
        protocol: "https",
        hostname: "placehold.co",
        port: "",
        pathname: "/**",
      },
    ],
  },

  async redirects() {
    return [
      {
        source: "/manual-testing",
        destination: "/manual-testing-services",
        permanent: true,
      },
      {
        source: "/our-clients",
        destination: "/case-studies",
        permanent: true,
      },
      {
        source: "/contact",
        destination: "/contact-us",
        permanent: true,
      },
      {
        source: "/tools",
        destination: "/technology-stack",
        permanent: true,
      },
      // Mumbai Station Redirects
      { source: "/software-qa-testing-services-in-andheri", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-bandra", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-bhandup", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-borivali", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-byculla", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-charni-road", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-chinchpokli", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-churchgate", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-cotton-green", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-cst", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-currey-road", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-dadar", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-dahisar", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-dockyard-road", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-ghatkopar", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-goregaon", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-grant-road", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-jogeshwari", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-kandivali", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-kanjurmarg", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-khar-road", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-kings-circle", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-kurla", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-lower-parel", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-mahalaxmi", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-mahim", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-malad", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-marine-lines", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-masjid-bandar", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-matunga-road", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-mumbai-central", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-mulund", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-nahur", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-prabhadevi", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-ram-mandir", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-reay-road", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-sandhurst-road", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-santacruz", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-sewri", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-sion", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-vidyavihar", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-vikhroli", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-vile-parle", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-wadala-road", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-bhayandar", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-diva", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-dombivli", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-kalwa", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-kalyan", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-kopar", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-mira-road", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-mumbra", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-naigaon", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-nalasopara", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-navi-mumbai", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-thakurli", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-thane", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-vasai", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/software-qa-testing-services-in-virar", destination: "/software-qa-testing-services-in-mumbai", permanent: true },
      { source: "/kanishka-software-case-study", destination: "/kanishka-mobile-app", permanent: true },
      { source: "/blog/tag/what-is-volume-testing-in-software-testing", destination: "/blog/post/volume-testing-managing-high-data-loads-efficiently", permanent: true },
      { source: "/blog/tag/device-energy-profiling", destination: "/blog/post/battery-power-testing-for-smart-devices-optimization-guide", permanent: true },
      { source: "/blog/tag/manual-vs-automated-regression-testing", destination: "/blog/post/automated-regression-testing-faster-smarter-qa-cycles", permanent: true },
      { source: "/blog/tag/selecting-testing-tools", destination: "/technology-stack", permanent: true },
      { source: "/blog/tag/exploratory-regression-testing", destination: "/blog/post/bug-discovery-find-hidden-defects-with-heuristic-exploratory-testing", permanent: true },
      { source: "/blog/tag/testriq-iot-testing-services", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/tag/compatibility-testing", destination: "/blog/post/a-complete-guide-to-compatibility-testing-in-manual-software-qa", permanent: true },
      { source: "/blog/tag/user-experience-testing", destination: "/blog/post/user-experience-testing-for-smart-devices-usability-accessibility", permanent: true },
      { source: "/blog/tag/mobile-learning", destination: "/blog/post/mobile-learning-optimization-enhancing-e-learning-platforms-for-mobile-devices", permanent: true },
      { source: "/blog/tag/cyber-threats", destination: "/blog/post/iot-security-validation-protecting-devices-from-cyber-threats", permanent: true },

      // Blog & Service Redirects
      { source: "/blog/tag/regression-automation-qa", destination: "/blog/post/automated-regression-testing-faster-smarter-qa-cycles", permanent: true },
      { source: "/blog/tag/mobile-testing-challenges", destination: "/blog/category/mobile-application-testing", permanent: true },
      { source: "/blog/tag/load-testing-lms", destination: "/blog/post/scalability-testing-for-learning-management-systems-lms-ensuring-a-smooth-experience-for-all-users", permanent: true },
      { source: "/blog/tag/usability-investigation", destination: "/blog/post/usability-investigation-how-exploratory-testing-elevates-ux", permanent: true },
      { source: "/blog/category/Iot Appliances & App Testing Service", destination: "/iot-appliances-and-apps-testing-services", permanent: true },
      { source: "/blog/tag/robotic-navigation-qa", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/medical-software-qa", destination: "/healthcare-testing-services", permanent: true },
      { source: "/services/api-testing", destination: "/api-testing", permanent: true },
      { source: "/blog/tag/mvp-security", destination: "/blog/post/security-validation-in-mvp-startup-qa-best-practices", permanent: true },
      { source: "/blog/tag/hipaa-compliance-verification", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/video-user-engagement", destination: "/blog/post/user-experience-testing-for-smart-devices-usability-accessibility", permanent: true },
      { source: "/blog/tag/lms-video-validation", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/interactive-video-testing", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/e-learning-video-qa", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/video-performance-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/video-streaming-quality", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/video-content-testing", destination: "/manual-testing-services", permanent: true },
      { source: "/blog/tag/autonomous-robot-testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/security-testing-best-practices", destination: "/blog/post/security-validation-in-mvp-startup-qa-best-practices", permanent: true },
      { source: "/blog/tag/qa", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/scalability-testing-best-practices", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/automation-testing-learning", destination: "/blog/post/how-much-time-do-we-need-to-learn-automation-testing", permanent: true },
      { source: "/blog/tag/gazebo-simulator-testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/lms-performance-optimization", destination: "/blog/post/scalability-testing-for-learning-management-systems-lms-ensuring-a-smooth-experience-for-all-users", permanent: true },
      { source: "/blog/tag/infrastructureascode", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/load-testing-healthcare-systems", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/ros2-node-validation", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/stress-testing-lms", destination: "/blog/post/scalability-testing-for-learning-management-systems-lms-ensuring-a-smooth-experience-for-all-users", permanent: true },
      { source: "/blog/tag/desktop-app-validation", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/software-testing-best-practices", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/owasp", destination: "/security-testing", permanent: true },

      // Batch 2 Mappings
      { source: "/blog/tag/robotics-functional-testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/hipaa-compliance-testing", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/responsive-testing", destination: "/web-application-testing-services", permanent: true },
      { source: "/blog/tag/desktop-app-optimization", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/robot-control-logic-testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/ehr-performance", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/iot-device-testing", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/tag/iot-qa-lifecycle", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/tag/benchmarking-desktop-applications", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/desktop-performance-qa", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/iot-testing-in-healthcare", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/vulnerability-scanning", destination: "/security-testing", permanent: true },
      { source: "/blog/category/API Testing", destination: "/api-testing", permanent: true },
      { source: "/blog/tag/mobile-app-security", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/multiplayer-qa", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/blog/tag/validation-and-optimization-in-desktop-app-testing", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/iot-performance-testing-services", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/tag/healthcare-software-reliability", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/patient-data-protection", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/mobile-testing-benchmarks", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/software-testing-reporting", destination: "/qa-documentation-services", permanent: true },
      { source: "/blog/tag/inclusive-learning", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/qa-reporting-in-mobile-apps", destination: "/qa-documentation-services", permanent: true },
      { source: "/blog/tag/risk-based-regression-testing", destination: "/regression-testing", permanent: true },
      { source: "/blog/tag/performance-optimization-healthcare", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/performancetesting", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/load-testinng", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/healthcare-system-response-time", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/qa-metrics-in-mobile-testing", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/e-learning-platform-scalability", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/startup-qa", destination: "/launchfast-qa", permanent: true },
      { source: "/blog/tag/ros2-testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/types-of-website-testing", destination: "/web-application-testing-services", permanent: true },
      { source: "/blog/category/Web Development", destination: "/web-application-testing-services", permanent: true },
      { source: "/blog/tag/docker-ros-testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/benefits-of-automation-testing", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/retesting-desktop-apps", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/web-application-penetration-testing", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/lms-capacity-testing", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/iot-testing-types-and-tools", destination: "/iot-device-testing-services", permanent: true },
      { source: "/desktop-application-testing", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/video-game-qa", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/blog/tag/software-testing-strategies", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/mobile-app-testing-summary", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/continuous-regression-testing", destination: "/regression-testing", permanent: true },
      { source: "/blog/tag/e-learning-qa", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/qa-workflows", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/securitytesting", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/cost-efficiency-in-app-development", destination: "/launchfast-qa", permanent: true },
      { source: "/blog/tag/secure-qa", destination: "/security-testing", permanent: true },

      // Batch 3 Mappings
      { source: "/blog/tag/cloud-enabled-performance-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/desktop-testing-benchmarks", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/post/the-future-of-software-testing-top-trends-for-the-next-decadee", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/types-of-software-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/robotic-system-validation", destination: "/robotics-testing-services", permanent: true },
      { source: "/trust-certification", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/data-privacy", destination: "/security-testing", permanent: true },
      { source: "/Load Time Analysis", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/desktop-testing-summary", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/real-time-validation", destination: "/web-application-testing-services", permanent: true },
      { source: "/blog/tag/qa-techniques", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/qa-continuous-improvement", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/healthcare-system-scalability", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/session-based-exploratory-testing", destination: "/exploratory-testing", permanent: true },
      { source: "/blog/tag/cross-device-ux-testing", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/software-automation-trend", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/exploratory-testing-for-usability", destination: "/exploratory-testing", permanent: true },
      { source: "/blog/tag/usability-in-qa", destination: "/exploratory-testing", permanent: true },
      { source: "/blog/tag/user-experience-qa", destination: "/exploratory-testing", permanent: true },
      { source: "/blog/tag/itinfrastructure", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/ci-cd-regression-qa", destination: "/regression-testing", permanent: true },
      { source: "/blog/tag/continuous-quality-assurance", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/repetitive-strain-syndrome", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/qa-automation", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/regression-in-ci-cd", destination: "/regression-testing", permanent: true },
      { source: "/blog/tag/healthcare-app-testing", destination: "/healthcare-testing-services", permanent: true },
      { source: "/services/iot-testing", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/tag/game-qa", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/blog/tag/game-release-preparation", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/blog/tag/multiplayer-bugs", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/blog/tag/robotics-qa", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/post/what-tests-are-standard-in-desktop-application-testing-2", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/version-compatibility", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/owasp-top-10", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/hipaa-testing", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/software-qa-process", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/wcag-compliance", destination: "/web-application-testing-services", permanent: true },
      { source: "/blog/tag/ros-qa", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/automation-testing-beginners", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/iot-testing-protocols-explained", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/tag/automation-performance-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/phi-protection", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/defect-reporting-in-desktop-apps", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/desktop-qa-reporting", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/healthcare-performance-testing", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/lms-performance-monitoring", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/lms-scalability-testing", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/performance-testing-in-agile", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/terraform", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/scorm-compliance-testing", destination: "/e-learning-testing-services", permanent: true },

      // Batch 4 Mappings
      { source: "/blog/tag/scorm-and-xapi-qa", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/lms-testing", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/learning-analytics-testing", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/e-learning-analytics", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/robotic-testing-trend", destination: "/blog/post/functional-testing-for-robotic-systems-precision-sensors-control", permanent: true },
      { source: "/blog/tag/test-case-metrics", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/sql-injection-testing", destination: "/security-testing", permanent: true },
      { source: "/index.php", destination: "/", permanent: true },
      { source: "/blog/tag/iot-testing-tools-2024", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/tag/automation-in-compliance-testing", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/inclusive-design", destination: "/web-application-testing-services", permanent: true },
      { source: "/blog/tag/web-app-security-testing", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/final-reporting-in-mobile-app-testing", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/qa-process-steps", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/medical-device-performance", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/concurrent-user-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/secure-web-applications", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/devops-testing", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/self-healing-test-scripts", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/regression-testing-benefits", destination: "/regression-testing", permanent: true },
      { source: "/canva-case-study", destination: "/canva-design-platform", permanent: true },
      { source: "/blog/tag/cross-browser-validation", destination: "/web-application-testing-services", permanent: true },
      { source: "/blog/tag/robotic-software-testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/automation-testing-tools-timeline-to-learn-testing", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/response-time-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/post/mobile-app-performance-testing-best-practices", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/post/manual-testing-for-keyboard-navigation-accessibility", destination: "/blog/post/accessibility-testing-in-manual-testing-use-cases-techniques", permanent: true },
      { source: "/blog/tag/environment-validation", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/category/Robotics Testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/post/devsecops-integrating-security-in-your-ci-cd-pipeline", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/device-compatibility", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/browser-testing", destination: "/web-application-testing-services", permanent: true },
      { source: "/blog/tag/software-development", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/regression-analysis-in-qa", destination: "/regression-testing", permanent: true },
      { source: "/blog/category/Regression Testing", destination: "/regression-testing", permanent: true },
      { source: "/blog/tag/product-launch-qa", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/scalability-in-cloud-applications", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/secure-mvp-launch", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/multi-device-compatibility", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/category/Software Testing Tools", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/dry-run-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/defect-tracking", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/scalability-testing-in-software-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/performance-scalability", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/category/Mobile Application Testing", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/scalability-qa", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/ci-cd-automation-integration", destination: "/automation-testing-services", permanent: true },
      { source: "/ragnar-case-study", destination: "/ragnar-sports-platform", permanent: true },
      { source: "/blog/tag/section-508-compliance", destination: "/web-application-testing-services", permanent: true },
      { source: "/blog/tag/software-testing", destination: "/blog/category/qa-testing", permanent: true },

      // Batch 5 Mappings
      { source: "/blog/tag/cicd", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/category/Performance Testing Services", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/concurrency-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/post/sap-s4hana-testing-guide", destination: "/blog", permanent: true },
      { source: "/blog/tag/blazemeter-performance-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/best-load-testing-tools", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/robot-algorithm-validation", destination: "/blog/post/functional-testing-for-robotic-systems-precision-sensors-control", permanent: true },
      { source: "/blog/tag/compliance", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/post/spike-testing-strategies", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/post/stress-testing-guide", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/qa-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/mobile-qa-strategy", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/load-testing-best-practices", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/load-testing-strategies", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/iot-performance-testing-cloud", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/tag/educational-platform-accessibility", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/post/load-testing-strategies-best-practices", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/ci-cd", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/post/api-testing-tools-guide-for-modern-web-and-mobile-apps", destination: "/api-testing", permanent: true },
      { source: "/blog/tag/hipaa-compliance", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/post/manual-accessibility-auditing-techniques", destination: "/manual-testing-services", permanent: true },
      { source: "/dating-apps-certification", destination: "/dating-app-certification", permanent: true },
      { source: "/blog/tag/gatling", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/testing-methodologies", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/software-debugging", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/test-run-implementation", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/learn-mobile-testing", destination: "/mobile-application-testing", permanent: true },
      { source: "/gaming-app-testing-service", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/blog/tag/software-stability-qa", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/testing-tag", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/mobile-app-testing-tools", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/regression-testing-in-agile", destination: "/regression-testing", permanent: true },
      { source: "/blog/tag/penetration-testing", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/endpoint-validation", destination: "/api-testing", permanent: true },
      { source: "/blog/tag/ci-cd-integration", destination: "/automation-testing-services", permanent: true },
      { source: "/services/software-testing-guide", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/services/regression-testing", destination: "/regression-testing", permanent: true },
      { source: "/services/etl-testing", destination: "/etl-testing-services", permanent: true },
      { source: "/certifications/dating-apps", destination: "/dating-app-certification", permanent: true },
      { source: "/certifications/trading-apps", destination: "/trading-apps-certification", permanent: true },
      { source: "/certifications", destination: "/", permanent: true },
      { source: "/industries/telecommunication-testing", destination: "/telecommunications-testing-services", permanent: true },
      { source: "/blog/tag/cloud-connectivity", destination: "/automation-testing-services", permanent: true },
      { source: "/services/web-application-testing", destination: "/web-application-testing-services", permanent: true },
      { source: "/certifications/matrimonial-apps", destination: "/matrimonial-apps-certification", permanent: true },
      { source: "/industries/healthcare-testing", destination: "/healthcare-testing-services", permanent: true },
      { source: "/services/launchfast-qa", destination: "/launchfast-qa", permanent: true },
      { source: "/industries/banking-finance-testing", destination: "/banking-finance-industry-testing-services", permanent: true },
      { source: "/services/robotics-testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/services/automation-testing", destination: "/automation-testing-services", permanent: true },

      // Batch 6 Mappings
      { source: "/industries/iot-testing", destination: "/iot-device-testing-services", permanent: true },
      { source: "/services/smart-device-testing", destination: "/iot-device-testing-services", permanent: true },
      { source: "/certifications/shopping-apps", destination: "/shopping-apps-certification", permanent: true },
      { source: "/services/security-testing", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/automation-framework", destination: "/automation-testing-services", permanent: true },
      { source: "/services/qa-documentation", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/services/desktop-application-testing", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/industries/ecommerce-testing", destination: "/e-commerce-testing-services", permanent: true },
      { source: "/blog/tag/data-synchronization", destination: "/data-analysis-services", permanent: true },
      { source: "/services/manual-testing", destination: "/manual-testing-services", permanent: true },
      { source: "/industries/elearning-testing", destination: "/e-learning-testing-services", permanent: true },
      { source: "/services/performance-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/services/ai-application-testing", destination: "/ai-application-testing", permanent: true },
      { source: "/services/data-analysis", destination: "/data-analysis-services", permanent: true },
      { source: "/industries/gaming-testing", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/services/mobile-application-testing", destination: "/mobile-application-testing", permanent: true },
      { source: "/services/corporate-qa-training", destination: "/corporate-qa-training", permanent: true },
      { source: "/blog/archive/2024", destination: "/blog", permanent: true },
      { source: "/blog/tag/resource-utilization-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/multiplayer-optimization", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/usability-testing", destination: "/exploratory-testing", permanent: true },
      { source: "/blog/tag/load-testing-guide", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/ci/cd-testing", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/cross-platform-regression-testing", destination: "/blog/post/cross-platform-regression-testing-ensuring-consistency-across-devices-os", permanent: true },
      { source: "/blog/tag/database-validation", destination: "/data-analysis-services", permanent: true },
      { source: "/blog/post/5g-mobile-app-testing-strategies-for-smooth-performance-in-2025-2", destination: "/blog/post/5g-mobile-app-testing-strategies-for-smooth-performance-in-2025", permanent: true },
      { source: "/blog/post/cicd-integration-with-automated-tests", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/post/game-testing-service-for-android-and-ios", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/blog/post/hipaa-compliance-testing-guide", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/post/top-5-reasons-to-choose-our-ai-testing-services", destination: "/ai-application-testing", permanent: true },
      { source: "/blog/post/version-compatibility-testing-best-practices", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/accessibility-testing", destination: "/web-application-testing-services", permanent: true },
      { source: "/automation-testing", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/category/performance-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/post/augmented-reality-ar-app-testing-tips", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/blog/post/best-practices-for-mobile-uiux-testing", destination: "/blog/post/best-practices-for-mobile-ui-ux-testing", permanent: true },
      { source: "/blog/post/cybersecurity-testing-solutions", destination: "/security-testing", permanent: true },
      { source: "/blog/post/do-you-think-that-software-testing-is-a-destructive-activityy", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/gdpr-compliance-testing", destination: "/security-testing", permanent: true },
      { source: "/blog/post/how-to-test-mobile-app-security-techniques-and-tools", destination: "/security-testing", permanent: true },
      { source: "/blog/post/network-testing-tools-and-techniques", destination: "/blog/category/performance-testing-services", permanent: true },
      { source: "/blog/post/performance-testing-for-mobile-apps-challenges-and-tools", destination: "/performance-testing-services", permanent: true },
      { source: "/ecommerce-testing-service", destination: "/e-commerce-testing-services", permanent: true },
      { source: "/elearning-testing-service", destination: "/e-learning-testing-services", permanent: true },
      { source: "/etl-testing", destination: "/etl-testing-services", permanent: true },
      { source: "/healthcare-testing-service", destination: "/healthcare-testing-services", permanent: true },
      { source: "/integration-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/iomt-testing", destination: "/iot-device-testing-services", permanent: true },
      { source: "/iot-appliances-app-testing-service", destination: "/iot-device-testing-services", permanent: true },
      { source: "/software-testing-services/", destination: "/blog/category/qa-testing", permanent: true },

      // Batch 7 Mappings
      { source: "/web-application-testing", destination: "/web-application-testing-services", permanent: true },
      { source: "/banking-finance-testing-service", destination: "/banking-finance-industry-testing-services", permanent: true },
      { source: "/blog/post/top-cross-browser-testing-tools-2025", destination: "/blog/category/web-app-testing", permanent: true },
      { source: "/iot-testing", destination: "/iot-device-testing-services", permanent: true },
      { source: "/regulatory-testing", destination: "/security-testing", permanent: true },
      { source: "/software-qa-testing-services-in-windows", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/telecommunication-testing-service", destination: "/telecommunications-testing-services", permanent: true },
      { source: "/blog/tag/bug-discovery-in-qa", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/functional-testing", destination: "/manual-testing-services", permanent: true },
      { source: "/services", destination: "/", permanent: true },
      { source: "/blog/tag/performance-testing-tools", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/performance-testing-services", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/mobile-app-testing-services", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/secure-development", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/postman", destination: "/api-testing", permanent: true },
      { source: "/blog/post/self-healing-test-automation-what-it-is-and-why-it-matters-2", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/post/best-software-testing-companies-in-mumbai-for-2025-reviews-comparison-2", destination: "/blog/post/best-software-testing-companies-in-mumbai-for-2025-reviews-comparison", permanent: true },
      { source: "/blog/post/cloud-integration-testing-for-iot-aws-iot-azure-iot-google-iot-core-2", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/post/which-type-of-mobile-applications-can-be-tested-by-appium", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/blog", has: [{ type: 'query', key: 'page', value: '15' }], destination: "/blog", permanent: true },
      { source: "/blog/post/validation-optimization-in-desktop-app-testing-retesting-performance-ux-assurances", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/performance-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/cyber", destination: "/security-testing", permanent: true },
      { source: "/blog/post/372-2", destination: "/blog", permanent: true },
      { source: "/blog/tag/exploratory-testing", destination: "/manual-testing-services", permanent: true },
      { source: "/blog/tag/cloud-testing", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/manual-testing", destination: "/manual-testing-services", permanent: true },
      { source: "/blog/tag/devtestops", destination: "/automation-testing-services", permanent: true },
      { source: "/\\$", destination: "/", permanent: true },
      { source: "/&", destination: "/", permanent: true },
      { source: "/mobile-application-testing-services", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/post/how-to-test-a-websites-performance-2", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/post/what-is-the-latest-thing-going-on-in-automation-testing-2", destination: "/automation-testing-services", permanent: true },
      { source: "/quality-assurance-services/", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/defect-discovery", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/ultrasonic-testing-techniques", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/which-iot-platform-is-the-most-secure", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/tag/desktop-application-qa", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/tag/horizontal-scaling", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/mobile-qa-strategies", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/defect-reporting", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/digital-inclusion", destination: "/web-application-testing-services", permanent: true },
      { source: "/blog/tag/load-testing-frameworks", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/graphql-api-testing", destination: "/api-testing", permanent: true },
      { source: "/blog/post/performance-bottlenecks-in-web-apps-how-to-identify-them", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/defect-detection", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/data-encryption-lms", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/enterprise-application-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/iot-data-privacy", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/post/remote-testing-strategies-and-tools", destination: "/mobile-application-testing", permanent: true },

      // Batch 8 Mappings
      { source: "/blog/post/integrating-performance-testing-into-ci-cd-for-devops-success-2", destination: "/blog/post/integrating-performance-testing-into-ci-cd-for-devops-success", permanent: true },
      { source: "/blog/tag/mobile-learning-optimization", destination: "/blog/post/mobile-learning-optimization-enhancing-e-learning-platforms-for-mobile-devices", permanent: true },
      { source: "/blog/tag/devops-qa-strategy", destination: "/blog/category/automation-testing-services", permanent: true },
      { source: "/blog/tag/graphql-automation", destination: "/blog/post/graphql-api-testing-strategies-for-queries-mutations-performance", permanent: true },
      { source: "/blog/tag/data-flow-validation", destination: "/data-analysis-services", permanent: true },
      { source: "/blog/tag/database-testing", destination: "/data-analysis-services", permanent: true },
      { source: "/blog/tag/cross-browser-testing", destination: "/blog/category/web-app-testing", permanent: true },
      { source: "/blog/tag/device-security", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/graphql-performance-testing", destination: "/blog/post/graphql-api-testing-strategies-for-queries-mutations-performance", permanent: true },
      { source: "/blog/post/healthcare-data-protection-best-practices", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/post/iot-in-software-quality-assurance", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/post/weld-inspection-testing-methods", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/magnetic-particle-inspection-techniques", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/control-system-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/firebase-profiler", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/future-of-software-testing", destination: "/blog", permanent: true },
      { source: "/blog/tag/healthcare-app-security", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/performance-and-load-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/mobile-app-optimization", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/mobile-app-test-cases", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/mobile-app-responsiveness", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/qa-best-practices", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/regression-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/end-to-end-qa-scenarios", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/sdlc", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/creating-compatibility-matrix-for-software-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/future-of-ai", destination: "/ai-application-testing", permanent: true },
      { source: "/blog/tag/k6", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/author/Testriq", has: [{ type: 'query', key: 'page', value: '18' }], destination: "/blog", permanent: true },
      { source: "/blog/tag/e-learning-optimization", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/endurance-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/post/penetration-testing-services-guide", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/robot-functional-testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/exploratory-testing-techniques", destination: "/manual-testing-services", permanent: true },
      { source: "/blog/tag/mobile-performance-qa", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/post/common-mobile-app-security-flaws-and-how-to-prevent-them", destination: "/blog/post/how-to-test-mobile-app-security-techniques-tools", permanent: true },
      { source: "/blog/author/Testriq", has: [{ type: 'query', key: 'page', value: '16' }], destination: "/blog", permanent: true },
      { source: "/blog/tag/automation-tools", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/automation-testing-innovation", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/author/Testriq", has: [{ type: 'query', key: 'page', value: '15' }], destination: "/blog", permanent: true },
      { source: "/blog/tag/mobile-testing-trends", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/author/Testriq", has: [{ type: 'query', key: 'page', value: '8' }], destination: "/blog", permanent: true },
      { source: "/blog/tag/stress-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/devops", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/software-testing-challenges", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/emulator-testing", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/tag/future-of-robotic-testing", destination: "/robotics-testing-services", permanent: true },
      { source: "/blog/tag/scriptless-automation", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/future-of-qa", destination: "/blog", permanent: true },
      { source: "/regression-testings", destination: "/blog/category/qa-testing", permanent: true },

      // Batch 9 Mappings
      { source: "/automation-testing/", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/software-testing-company", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/performance-optimization", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/movement-precision-testing", destination: "/blog/post/functional-testing-for-robotic-systems-precision-sensors-control", permanent: true },
      { source: "/blog/post/what-is-performance-testing-in-software-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/a/b-testing", destination: "/exploratory-testing", permanent: true },
      { source: "/blog/tag/e-learning-platform-performance", destination: "/e-learning-testing-services", permanent: true },
      { source: "/blog/tag/performance-analysis", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/qa-technologies", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/blog", destination: "/blog", permanent: true },
      { source: "/blog/tag/game-hacking-prevention", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/blog/tag/cloud-based-regression-execution", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/cybersecurity-for-games", destination: "/security-testing", permanent: true },
      { source: "/case-study/canva-case-study", destination: "/canva-design-platform", permanent: true },
      { source: "/blog/tag/end-to-end-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/software-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/data-transformation-testing", destination: "/data-analysis-services", permanent: true },
      { source: "/case-study/smart-doorbell-case-study", destination: "/smart-video-doorbell-qa-case-study", permanent: true },
      { source: "/case-study/indo-wings-case-study", destination: "/indo-wings-security-testing-case-study", permanent: true },
      { source: "/case-study/ragnar-case-study", destination: "/ragnar-sports-platform", permanent: true },
      { source: "/data-quality-testing-in-etl", destination: "/data-analysis-services", permanent: true },
      { source: "/contact-uss", destination: "/contact-us", permanent: true },
      { source: "/etl-testing-tools-frameworks-2025", destination: "/etl-testing-services", permanent: true },
      { source: "/automated-etl-testing-best-practices", destination: "/blog/post/automated-etl-testing", permanent: true },
      { source: "/etl-testing-for-big-data", destination: "/data-analysis-services", permanent: true },
      { source: "/data-loading-testing", destination: "/data-analysis-services", permanent: true },
      { source: "/etl-performance-testing", destination: "/etl-testing-services", permanent: true },
      { source: "/e-learning-testing-servicess", destination: "/e-learning-testing-services", permanent: true },
      { source: "/etl-security-testing", destination: "/security-testing", permanent: true },
      { source: "/blog/tag/extreme-load-testing", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/postblog/post/functional-testing-for-robotic-systems-precision-sensors-control", destination: "/blog/post/functional-testing-for-robotic-systems-precision-sensors-control", permanent: true },
      { source: "/blog/tag/ci/cd-integration-testing", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/testing", destination: "/blog", permanent: true },
      { source: "/blog/tag/energy-optimization", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/charging-performance", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/tag/battery-life", destination: "/mobile-application-testing", permanent: true },
      { source: "/blog/future-of-manual-testing", destination: "/manual-testing-services", permanent: true },
      { source: "/blog/tag/end-to-end-api-validation", destination: "/api-testing", permanent: true },
      { source: "/blog/tag/best-qa-tools-for-automation", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/highly-used-testing-tools-in-2024", destination: "/automation-testing-services", permanent: true },
      { source: "/blog/tag/healthcare-app-qa", destination: "/healthcare-testing-services", permanent: true },
      { source: "/blog/tag/eggplant-iot-testing", destination: "/iot-device-testing-services", permanent: true },
      { source: "/blog/tag/performance-validation", destination: "/performance-testing-services", permanent: true },
      { source: "/blog/principles-of-exploratory-testing", destination: "/blog/post/what-are-the-principles-of-exploratory-testing", permanent: true },
      { source: "/blog/why-do-we-need-exploratory-testing", destination: "/blog/post/what-are-the-principles-of-exploratory-testing", permanent: true },
      { source: "/blog/load-testing-desktop-applications", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/blog/exploratory-software-testing", destination: "/manual-testing-services", permanent: true },

      // Cleanup Redirects (Fixing cached 301s to 404 paths)
      { source: "/case-studies/canva-design-platform", destination: "/canva-design-platform", permanent: true },
      { source: "/case-studies/smart-video-doorbell-qa-case-study", destination: "/smart-video-doorbell-qa-case-study", permanent: true },
      { source: "/case-studies/indo-wings-security-testing-case-study", destination: "/indo-wings-security-testing-case-study", permanent: true },
      { source: "/case-studies/ragnar-sports-platform", destination: "/ragnar-sports-platform", permanent: true },
      { source: "/ai-testing-services", destination: "/ai-application-testing", permanent: true },
      { source: "/desktop-app-testing-services", destination: "/desktop-application-testing-services", permanent: true },
      { source: "/ecommerce-testing-services", destination: "/e-commerce-testing-services", permanent: true },
      { source: "/database-testing", destination: "/data-analysis-services", permanent: true },
      { source: "/ar-vr-testing-services", destination: "/gaming-app-testing-services", permanent: true },
      { source: "/sustainability-testing-services", destination: "/performance-testing-services", permanent: true },
      { source: "/big-data-testing-services", destination: "/data-analysis-services", permanent: true },
      { source: "/compliance-testing-services", destination: "/security-testing", permanent: true },
      { source: "/medical-device-testing-services", destination: "/healthcare-testing-services", permanent: true },
      { source: "/software-testing-services", destination: "/blog/category/qa-testing", permanent: true },

      // Batch 10: Fixes for User Reported Broken Links (Feb 2026) - Mapped to Verified CMS Content
      { source: "/blog/tag/xss-prevention", destination: "/blog/category/security-testing", permanent: true },
      { source: "/blog/tag/risk-assessment-in-testing", destination: "/blog/category/manual-testing", permanent: true }, // Fallback to Manual/Strategy
      { source: "/blog/tag/mobile-app-automation-testing-tools", destination: "/blog/category/mobile-application-testing", permanent: true },
      { source: "/blog/tag/jmeter-performance-testing-2024", destination: "/blog/category/performance-testing-services", permanent: true },
      { source: "/blog/tag/responsive-design-testing", destination: "/blog/category/web-app-testing", permanent: true },
      { source: "/blog/tag/conversion-optimization", destination: "/blog/category/web-app-testing", permanent: true },
      { source: "/blog/post/using-assistive-technologies-in-accessibility-testing", destination: "/blog/category/web-app-testing", permanent: true }, // Accessibility usually under Web
      { source: "/blog/tag/mobile-usability-testing", destination: "/blog/category/mobile-application-testing", permanent: true },
      { source: "/blog/tag/top-software-testing-tools-2024", destination: "/blog/category/software-testing-tools", permanent: true },
      { source: "/blog/tag/streamlining", destination: "/blog/category/automation-testing-services", permanent: true },
      { source: "/blog/tag/iso-10218-compliance", destination: "/blog/category/robotics-testing", permanent: true },
      { source: "/blog/post/sap-testing-services", destination: "/blog/category/automation-testing-services", permanent: true },
      { source: "/blog/tag/human-robot-interaction", destination: "/blog/category/robotics-testing", permanent: true },
      { source: "/blog/tag/qa-performance-testing", destination: "/blog/category/performance-testing-services", permanent: true },
      { source: "/blog/tag/ios-app-automation", destination: "/blog/category/ios-app-testing", permanent: true },
      { source: "/blog/tag/mobile-app-test", destination: "/blog/category/mobile-application-testing", permanent: true },
      { source: "/blog/tag/network-resilience", destination: "/blog/category/performance-testing-services", permanent: true },
      { source: "/blog/tag/locust-automation", destination: "/blog/category/performance-testing-services", permanent: true },
      { source: "/blog/tag/secure-payment-testing", destination: "/blog/category/security-testing", permanent: true },
      { source: "/blog/tag/open-source-testing-tools-2024", destination: "/blog/category/software-testing-tools", permanent: true },
      { source: "/blog/tag/best-mobile-app-testing-tools", destination: "/blog/category/mobile-application-testing", permanent: true },
      { source: "/blog/tag/regression-automation", destination: "/blog/category/regression-testing", permanent: true },
      { source: "/blog/category/Iot Appliances & App Testing Service", destination: "/blog/category/iot-appliances-app-testing-service", permanent: true },
      { source: "/blog/category/Iot%20Appliances%20&%20App%20Testing%20Service", destination: "/blog/category/iot-appliances-app-testing-service", permanent: true },
      { source: "/blog/tag/regression-automation-qa", destination: "/blog/category/regression-testing", permanent: true },
      { source: "/blog/tag/mobile-testing-challenges", destination: "/blog/category/mobile-application-testing", permanent: true },
      { source: "/blog/tag/software-testing-best-practices", destination: "/blog/category/best-practices", permanent: true },
      { source: "/blog/tag/software-testing-strategies", destination: "/blog/category/best-practices", permanent: true },
      { source: "/blog/post/the-future-of-software-testing-top-trends-for-the-next-decadee", destination: "/blog/post/the-future-of-software-testing-top-trends-for-the-next-decade", permanent: true },
      { source: "/blog/tag/types-of-software-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/Load Time Analysis", destination: "/blog/category/performance-testing-services", permanent: true },
      { source: "/blog/tag/qa-continuous-improvement", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/repetitive-strain-syndrome", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/software-qa-process", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/test-case-metrics", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/product-launch-qa", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/dry-run-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/defect-tracking", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/software-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/qa-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/testing-methodologies", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/software-debugging", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/test-run-implementation", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/software-stability-qa", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/testing-tag", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/services/software-testing-guide", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/services/qa-documentation", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/version-compatibility-testing-best-practices", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/5g-mobile-app-testing-strategies-for-smooth-performance-in-2025-2", destination: "/blog/post/5g-mobile-app-testing-strategies-for-smooth-performance-in-2025", permanent: true },
      { source: "/integration-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/software-testing-services/", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/network-testing-tools-and-techniques", destination: "/blog/category/performance-testing-services", permanent: true },
      { source: "/blog/post/best-practices-for-mobile-uiux-testing", destination: "/blog/post/best-practices-for-mobile-ui-ux-testing", permanent: true },
      { source: "/blog/post/do-you-think-that-software-testing-is-a-destructive-activityy", destination: "/blog/post/do-you-think-that-software-testing-is-a-destructive-activity", permanent: true },
      { source: "/blog/post/top-cross-browser-testing-tools-2025", destination: "/blog/category/web-app-testing", permanent: true },
      { source: "/blog/tag/bug-discovery-in-qa", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/best-software-testing-companies-in-mumbai-for-2025-reviews-comparison-2", destination: "/blog/post/best-software-testing-companies-in-mumbai-for-2025-reviews-comparison", permanent: true },
      { source: "/quality-assurance-services/", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/defect-discovery", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/ultrasonic-testing-techniques", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/defect-reporting", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/defect-detection", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/enterprise-application-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/integrating-performance-testing-into-ci-cd-for-devops-success-2", destination: "/blog/post/integrating-performance-testing-into-ci-cd-for-devops-success", permanent: true },
      { source: "/blog/tag/mobile-learning-optimization", destination: "/blog/post/mobile-learning-optimization-enhancing-e-learning-platforms-for-mobile-devices", permanent: true },
      { source: "/blog/tag/devops-qa-strategy", destination: "/blog/category/automation-testing-services", permanent: true },
      { source: "/blog/tag/graphql-automation", destination: "/blog/category/api-testing", permanent: true },
      { source: "/blog/tag/cross-browser-testing", destination: "/blog/category/web-app-testing", permanent: true },
      { source: "/blog/tag/graphql-performance-testing", destination: "/blog/post/graphql-api-testing-strategies-for-queries-mutations-performance", permanent: true },
      { source: "/blog/post/weld-inspection-testing-methods", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/magnetic-particle-inspection-techniques", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/control-system-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/qa-best-practices", destination: "/blog/category/best-practices", permanent: true },
      { source: "/blog/tag/end-to-end-qa-scenarios", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/sdlc", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/creating-compatibility-matrix-for-software-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/post/common-mobile-app-security-flaws-and-how-to-prevent-them", destination: "/blog/post/common-mobile-app-security-flaws-and-how-to-prevent-them-2", permanent: true },
      { source: "/blog/tag/software-testing-challenges", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/regression-testings", destination: "/blog/category/regression-testing", permanent: true },
      { source: "/blog/tag/software-testing-company", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/qa-technologies", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/blog/tag/end-to-end-testing", destination: "/blog/category/qa-testing", permanent: true },
      { source: "/case-study/smart-doorbell-case-study", destination: "/smart-video-doorbell-qa-case-study", permanent: true },
      { source: "/case-study/indo-wings-case-study", destination: "/indo-wings-security-testing-case-study", permanent: true },
      { source: "/automated-etl-testing-best-practices", destination: "/blog/post/automated-etl-testing", permanent: true },
      { source: "/blog/principles-of-exploratory-testing", destination: "/blog/post/what-are-the-principles-of-exploratory-testing", permanent: true },
      { source: "/blog/why-do-we-need-exploratory-testing", destination: "/blog/category/exploratory-testing", permanent: true },

      // Batch 11: Fix Invalid Category redirects (Spaces in source)
      { source: "/blog/category/API Testing", destination: "/blog/category/api-testing", permanent: true },
      { source: "/blog/category/Web Development", destination: "/blog/category/web-development", permanent: true },
      { source: "/blog/category/Robotics Testing", destination: "/blog/category/robotics-testing", permanent: true },
      { source: "/blog/category/Regression Testing", destination: "/blog/category/regression-testing", permanent: true },
      { source: "/blog/category/Software Testing Tools", destination: "/blog/category/software-testing-tools", permanent: true },
      { source: "/blog/category/Mobile Application Testing", destination: "/blog/category/mobile-application-testing", permanent: true },
      { source: "/blog/category/Performance Testing Services", destination: "/blog/category/performance-testing-services", permanent: true },

      // Critical Fix: Redirecting the missing guide page itself to Blog
      { source: "/software-testing-guide", destination: "/blog", permanent: true },
    ];
  },
};

export default withBundleAnalyzer(nextConfig);
