/**
 * Sanity build snapshot refresher.
 *
 * Fetches all slug lists needed by `generateStaticParams` across the app and
 * writes them to `src/lib/sanity-build-snapshot.json`. Committing the resulting
 * file means Vercel builds can run without calling Sanity for slug enumeration —
 * eliminating the dominant source of Sanity free-tier 402 quota burn.
 *
 * Usage:
 *   # Make sure SANITY_API_TOKEN (or NEXT_PUBLIC_SANITY_PROJECT_ID etc) is in .env.local
 *   npm run sanity:snapshot
 *
 *   # Then review + commit the changed JSON:
 *   git diff src/lib/sanity-build-snapshot.json
 *   git add src/lib/sanity-build-snapshot.json
 *   git commit -m "chore: refresh Sanity build snapshot"
 *
 * Recommended cadence: refresh whenever a batch of new posts/case studies lands
 * in Sanity Studio. Or wire a daily GitHub Action that runs this + auto-PRs.
 *
 * Notes:
 *  - Uses `useCdn: false` so we get the freshest data, not stale CDN cache.
 *  - 5 fetches total (post, caseStudy, author, category, tag) — very low quota cost.
 *  - Each fetch returns only slug strings (no body content), so fast + cheap.
 */

import { createClient } from 'next-sanity';
import * as dotenv from 'dotenv';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

// Load .env.local first (Next.js convention), fall back to .env
dotenv.config({ path: '.env.local' });
dotenv.config();

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || '7hxinmig';
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production';
const apiVersion = process.env.NEXT_PUBLIC_SANITY_API_VERSION || '2024-01-01';

const client = createClient({
    projectId,
    dataset,
    apiVersion,
    useCdn: false, // bypass CDN — we want fresh data, and this query is rare anyway
    token: process.env.SANITY_API_TOKEN, // optional; reads work without token for public datasets
});

async function fetchSlugList(docType: string): Promise<string[]> {
    const query = `*[_type == "${docType}" && defined(slug.current)][].slug.current`;
    try {
        const result = await client.fetch<string[]>(query);
        return result || [];
    } catch (err) {
        console.error(`Failed to fetch ${docType} slugs:`, err);
        return [];
    }
}

async function main() {
    console.log(`Connecting to Sanity (projectId=${projectId}, dataset=${dataset})...`);

    const [postSlugs, caseStudySlugs, authorSlugs, categorySlugs, tagSlugs] = await Promise.all([
        fetchSlugList('post'),
        fetchSlugList('caseStudy'),
        fetchSlugList('author'),
        fetchSlugList('category'),
        fetchSlugList('tag'),
    ]);

    const snapshot = {
        generatedAt: new Date().toISOString(),
        note: 'Auto-generated by src/scripts/snapshot-sanity-slugs.ts. Commit this file. Refresh by running `npm run sanity:snapshot`.',
        postSlugs,
        caseStudySlugs,
        authorSlugs,
        categorySlugs,
        tagSlugs,
    };

    const filepath = resolve(process.cwd(), 'src/lib/sanity-build-snapshot.json');
    writeFileSync(filepath, JSON.stringify(snapshot, null, 2) + '\n');

    console.log(`✅ Snapshot written to ${filepath}`);
    console.log(`Counts:`);
    console.log(`  posts:        ${postSlugs.length}`);
    console.log(`  case studies: ${caseStudySlugs.length}`);
    console.log(`  authors:      ${authorSlugs.length}`);
    console.log(`  categories:   ${categorySlugs.length}`);
    console.log(`  tags:         ${tagSlugs.length}`);
    console.log(`  TOTAL:        ${postSlugs.length + caseStudySlugs.length + authorSlugs.length + categorySlugs.length + tagSlugs.length}`);

    if (postSlugs.length === 0 && caseStudySlugs.length === 0) {
        console.warn('⚠️  All lists empty. Sanity may be in 402 quota state OR token missing. Try again after quota resets.');
        process.exit(1);
    }
}

main().catch(err => {
    console.error('Snapshot generation failed:', err);
    process.exit(1);
});
